name: sklep_strony_internetowe
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.24.0
  provider: ^6.1.1
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2
  barcode_widget: ^2.0.4
  cupertino_icons: ^1.0.6
  intl: ^0.18.0
  page_view_indicators: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
